# Generated by Django 5.2.5 on 2026-06-06 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_platformsettings_app_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.CharField(choices=[('long_term', 'Longo Prazo'), ('short_term', 'Curto Prazo'), ('activities', 'Actividades')], default='long_term', max_length=20, verbose_name='Categoria do Plano'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='activated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Ativação'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='cycle_completed',
            field=models.BooleanField(default=False, verbose_name='Ciclo Concluído'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='payout_executed',
            field=models.BooleanField(default=False, verbose_name='Pago ao Saldo'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Nível'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('name', 'category')},
        ),
    ]
