# Generated by Django 5.2.5 on 2026-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_level_category_userlevel_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='accumulated_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crédito Acumulado Retido'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='days_processed',
            field=models.IntegerField(default=0, verbose_name='Dias Processados'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='last_task_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Processamento de Tarefa'),
        ),
    ]
