# Generated by Django 5.2.5 on 2026-06-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userlevel_accumulated_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userlevel', verbose_name='Nível Vinculado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Disponível'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subsidy_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo de Subsídios'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='level',
            name='daily_gain',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganho Diário'),
        ),
        migrations.AlterField(
            model_name='level',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Depósito'),
        ),
        migrations.AlterField(
            model_name='level',
            name='monthly_gain',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganho Mensal'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Nível (Ex: 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='deposit_instruction',
            field=models.TextField(verbose_name='Texto de instrução para depósito'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='history_text',
            field=models.TextField(verbose_name="Texto da página 'Sobre'"),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='whatsapp_link',
            field=models.URLField(verbose_name='Link do grupo de apoio do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='withdrawal_instruction',
            field=models.TextField(verbose_name='Texto de instrução para saque'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prêmio'),
        ),
        migrations.AlterField(
            model_name='task',
            name='earnings',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganhos'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='accumulated_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Crédito Acumulado Retido'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
    ]
