# Generated by Django 5.2.5 on 2026-07-24 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_user_level_alter_customuser_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_restricted',
            field=models.BooleanField(default=False, verbose_name='Usuário Restrito (Apenas Leitura no Blog)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagem da Publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Publicação da Comunidade',
                'verbose_name_plural': 'Publicações da Comunidade',
                'ordering': ['created_at'],
            },
        ),
    ]
