# Generated by Django 5.2.5 on 2026-07-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_is_restricted_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbankdetails',
            name='is_crypto',
            field=models.BooleanField(default=False, verbose_name='É Canal USDT/Crypto?'),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='IBAN',
            field=models.CharField(max_length=150, verbose_name='IBAN / Endereço da Wallet'),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Titular / Descrição do Canal'),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Nome do Banco / Rede USDT'),
        ),
    ]
